### ISSUE TITLE
§c[OP] §rHellsos joined the game; Failed to handle packet

### ISSUE THREAD

**Issue by zacekjakub** [MCServerTools/ServerTools-CORE#15]
Hi, I would like to show you probably a bug, the mod works well on our server, but when we join the server as OP, we get "internal server error" announced by the client and in server log is:

[23:04:33] [Server thread/INFO]: §c[OP] §rHellsos joined the game
[23:04:33] [Server thread/WARN]: Failed to handle packet for /hidden_ip:62482
java.lang.NullPointerException
        at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:101) ~[FMLProxyPacket.class:?]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) ~[ej.class:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) [lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
[23:04:33] [Server thread/INFO]: Hellsos lost connection: TextComponent{text='Internal server error', siblings=[], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null}}
[23:04:33] [Server thread/INFO]: §c[OP] §rHellsos left the game

Thank you very much,

Jakub

**Comment by matthewprenger** [comment]
I need the server log from when the players try to connect to be sure, but I'm fairly sure this is a Waila bug. ProfMobius has fixed it, but I'm not sure if he has released the fixed version yet.

**Comment by zacekjakub** [comment]
Here you are with FML log from right time, thank you. :) Btw I just realized it depends on B:"Color OP Messages"=true in the config file. When I set this to false, it is working.

# tail -150 fml-server-latest.log   
[02:52:36] [Server thread/ERROR] [FML/]: 9: ASM: INSTANCE onPlayerLogin(Lcpw/mods/fml/common/gameevent/PlayerEvent$PlayerLoggedInEvent;)V
[02:52:36] [Server thread/ERROR] [FML/]: 10: ASM: dmillerw.time.network.NetworkEventHandler@4db521ac onPlayerLogin(Lcpw/mods/fml/common/gameevent/PlayerEvent$PlayerLoggedInEvent;)V
[02:52:36] [Server thread/ERROR] [FML/]: 11: ASM: mods.immibis.chunkloader.DimensionalAnchors@2bf1849b onPlayerLogin(Lcpw/mods/fml/common/gameevent/PlayerEvent$PlayerLoggedInEvent;)V
[02:52:36] [Server thread/ERROR] [FML/]: 12: ASM: eu.thesociety.DragonbornSR.DragonsRadioMod.Handler.ServerEvent@793f95af userLoggedIn(Lcpw/mods/fml/common/gameevent/PlayerEvent$PlayerLoggedInEvent;)V
[02:52:36] [Server thread/ERROR] [FML/]: 13: ASM: twilightforest.TFEventListener@3a955cd4 playerLogsIn(Lcpw/mods/fml/common/gameevent/PlayerEvent$PlayerLoggedInEvent;)V
[02:52:36] [Server thread/ERROR] [FML/]: 14: ASM: info.servertools.core.chat.Motd@4bf85a22 onPlayerLogin(Lcpw/mods/fml/common/gameevent/PlayerEvent$PlayerLoggedInEvent;)V
[02:52:36] [Server thread/ERROR] [FML/]: HandshakeCompletionHandler exception
java.lang.NullPointerException
        at mcp.mobius.opis.events.PlayerTracker.getPlayerAccessLevel(PlayerTracker.java:45) ~[PlayerTracker.class:?]
        at mcp.mobius.opis.events.PlayerTracker.getPlayerAccessLevel(PlayerTracker.java:41) ~[PlayerTracker.class:?]
        at mcp.mobius.opis.network.enums.Message.canPlayerUseCommand(Message.java:130) ~[Message.class:?]
        at mcp.mobius.opis.network.PacketManager.validateAndSend(PacketManager.java:274) ~[PacketManager.class:?]
        at mcp.mobius.opis.events.PlayerTracker.onPlayerLogin(PlayerTracker.java:107) ~[PlayerTracker.class:?]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler_184_PlayerTracker_onPlayerLogin_PlayerLoggedInEvent.invoke(.dynamic) ~[?:?]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
        at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138) ~[EventBus.class:?]
        at cpw.mods.fml.common.FMLCommonHandler.firePlayerLoggedIn(FMLCommonHandler.java:550) ~[FMLCommonHandler.class:?]
        at net.minecraft.server.management.ServerConfigurationManager.a(ServerConfigurationManager.java:180) ~[oi.class:?]
        at cpw.mods.fml.common.network.handshake.NetworkDispatcher.completeServerSideConnection(NetworkDispatcher.java:173) ~[NetworkDispatcher.class:?]
        at cpw.mods.fml.common.network.handshake.NetworkDispatcher.completeHandshake(NetworkDispatcher.java:446) ~[NetworkDispatcher.class:?]
        at cpw.mods.fml.common.network.internal.HandshakeCompletionHandler.channelRead0(HandshakeCompletionHandler.java:17) ~[HandshakeCompletionHandler.class:?]
        at cpw.mods.fml.common.network.internal.HandshakeCompletionHandler.channelRead0(HandshakeCompletionHandler.java:11) ~[HandshakeCompletionHandler.class:?]
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) ~[SimpleChannelInboundHandler.class:?]
        at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
        at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [MessageToMessageDecoder.class:?]
        at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) [MessageToMessageCodec.class:?]
        at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
        at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) [DefaultChannelPipeline.class:?]
        at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) [EmbeddedChannel.class:?]
        at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:?]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) [lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
[02:52:36] [Server thread/ERROR] [FML/]: There was a critical exception handling a packet on channel FML
java.lang.NullPointerException
        at mcp.mobius.opis.events.PlayerTracker.getPlayerAccessLevel(PlayerTracker.java:45) ~[PlayerTracker.class:?]
        at mcp.mobius.opis.events.PlayerTracker.getPlayerAccessLevel(PlayerTracker.java:41) ~[PlayerTracker.class:?]
        at mcp.mobius.opis.network.enums.Message.canPlayerUseCommand(Message.java:130) ~[Message.class:?]
        at mcp.mobius.opis.network.PacketManager.validateAndSend(PacketManager.java:274) ~[PacketManager.class:?]
        at mcp.mobius.opis.events.PlayerTracker.onPlayerLogin(PlayerTracker.java:107) ~[PlayerTracker.class:?]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler_184_PlayerTracker_onPlayerLogin_PlayerLoggedInEvent.invoke(.dynamic) ~[?:?]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
        at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138) ~[EventBus.class:?]
        at cpw.mods.fml.common.FMLCommonHandler.firePlayerLoggedIn(FMLCommonHandler.java:550) ~[FMLCommonHandler.class:?]
        at net.minecraft.server.management.ServerConfigurationManager.a(ServerConfigurationManager.java:180) ~[oi.class:?]
        at cpw.mods.fml.common.network.handshake.NetworkDispatcher.completeServerSideConnection(NetworkDispatcher.java:173) ~[NetworkDispatcher.class:?]
        at cpw.mods.fml.common.network.handshake.NetworkDispatcher.completeHandshake(NetworkDispatcher.java:446) ~[NetworkDispatcher.class:?]
        at cpw.mods.fml.common.network.internal.HandshakeCompletionHandler.channelRead0(HandshakeCompletionHandler.java:17) ~[HandshakeCompletionHandler.class:?]
        at cpw.mods.fml.common.network.internal.HandshakeCompletionHandler.channelRead0(HandshakeCompletionHandler.java:11) ~[HandshakeCompletionHandler.class:?]
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) ~[SimpleChannelInboundHandler.class:?]
        at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[DefaultChannelHandlerContext.class:?]
        at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[DefaultChannelHandlerContext.class:?]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[MessageToMessageDecoder.class:?]
        at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) ~[MessageToMessageCodec.class:?]
        at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[DefaultChannelHandlerContext.class:?]
        at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[DefaultChannelHandlerContext.class:?]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) ~[DefaultChannelPipeline.class:?]
        at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) ~[EmbeddedChannel.class:?]
        at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:?]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) [lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]

**Comment by matthewprenger** [comment]
@zacekjakub Yeah thats the Opis bug. Make sure you're on the latest Opis because he may have fixed it. And yes turning off the OP colored messages is a workaround.
