### ISSUE TITLE
Ops cant connect

### ISSUE THREAD

**Issue by ravenboilinux** [MCServerTools/ServerTools-CORE#22]
Problem:
Since we installed ServerTools-Core, every ops get connection lost Internal server error

Server:
6GB of ram
Infinity 1.7 v 1.2.0 MC 1.7.10

logs:(this is a log where i restart the server and try to connect to it twice)
[18:10:37] [Server thread/INFO]: Starting minecraft server version 1.7.10
[18:11:27] [Server thread/INFO]: Loading properties
[18:11:27] [Server thread/INFO]: Default game type: SURVIVAL
[18:11:27] [Server thread/INFO]: Generating keypair
[18:11:27] [Server thread/INFO]: Starting Minecraft server on 158.85.69.136:25565
[18:11:54] [Server thread/INFO]: Preparing level "AutoCraft"
[18:11:56] [Server thread/INFO]: Preparing start region for level 0
[18:11:57] [Server thread/INFO]: Preparing spawn area: 72%
[18:11:57] [Server thread/INFO]: Done (3.867s)! For help, type "help" or "?"
[18:12:04] [AromaBackup/INFO]: [§1AromaBackup§r] Starting Backup. Server may lag for a bit!
[18:12:04] [AromaBackup/INFO]: [AromaBackup: Saved the world]
[18:12:04] [AromaBackup/INFO]: [AromaBackup: Turned off world auto-saving]
[18:12:08] [AromaBackup/INFO]: [§1AromaBackup§r] Server Backup Done!
[18:12:08] [AromaBackup/INFO]: [AromaBackup: Turned on world auto-saving]
[18:12:08] [AromaBackup/INFO]: [§1AromaBackup§r] Next scheduled backup in 60 minutes.
[18:12:24] [User Authenticator #1/INFO]: UUID of player MikeJoye is 12ab7edb-7a75-4111-867e-b6faff2032a1
[18:12:26] [Server thread/INFO]: MikeJoye[/108.84.135.62:53145] logged in with entity id 206 at (42.43945712383914, 78.0, -160.30000001192093)
[18:12:26] [Server thread/INFO]: §c[OP] §rMikeJoye joined the game
[18:12:26] [Server thread/WARN]: Failed to handle packet for /108.84.135.62:53145
java.lang.NullPointerException
	at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:101) ~[FMLProxyPacket.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) ~[ej.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) [lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
[18:12:27] [Server thread/INFO]: MikeJoye lost connection: TextComponent{text='Internal server error', siblings=[], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null}}
[18:12:27] [Server thread/INFO]: §c[OP] §rMikeJoye left the game
[18:15:24] [Server thread/INFO]: Unknown command. Try /help for a list of commands
[18:18:33] [User Authenticator #2/INFO]: UUID of player MikeJoye is 12ab7edb-7a75-4111-867e-b6faff2032a1
[18:18:35] [Server thread/INFO]: MikeJoye[/108.84.135.62:53493] logged in with entity id 310 at (42.43945712383914, 78.0, -160.30000001192093)
[18:18:35] [Server thread/INFO]: §c[OP] §rMikeJoye joined the game
[18:18:35] [Server thread/WARN]: Failed to handle packet for /108.84.135.62:53493
java.lang.NullPointerException
	at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:101) ~[FMLProxyPacket.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) ~[ej.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) [lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
[18:18:36] [Server thread/INFO]: MikeJoye lost connection: TextComponent{text='Internal server error', siblings=[], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null}}
[18:18:36] [Server thread/INFO]: §c[OP] §rMikeJoye left the game
[18:18:51] [Server thread/INFO]: Unknown command. Try /help for a list of commands

**Comment by ravenboilinux** [comment]
the issue was with opis and not servertools
[Issue](https://bitbucket.org/ProfMobius/opis/issue/98/opis-and-servertools)
