### ISSUE TITLE
Crash on server startup (NoSuchMethodError)

### ISSUE THREAD

**Issue by shortybsd** [MCServerTools/ServerTools-CORE#32]
Description: Exception in server tick loop

net.minecraftforge.fml.common.LoaderException: java.lang.NoSuchMethodError: ninja.leaping.configurate.hocon.HoconConfigurationLoader$Builder.setPath(Ljava/nio/file/Path;)Lninja/leaping/configurate/loader/AbstractConfigurationLoader$Builder;
	at net.minecraftforge.fml.common.LoadController.transition(LoadController.java:162)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:559)
	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:88)
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:320)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:112)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:441)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoSuchMethodError: ninja.leaping.configurate.hocon.HoconConfigurationLoader$Builder.setPath(Ljava/nio/file/Path;)Lninja/leaping/configurate/loader/AbstractConfigurationLoader$Builder;
	at info.servertools.core.util.STConfig.<init>(STConfig.java:66)
	at info.servertools.core.ServerToolsCore.onPreInit(ServerToolsCore.java:62)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:560)
	at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:211)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:189)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:556)
	... 5 more

**Comment by matthewprenger** [comment]
I'm guessing you downloaded the `-slim` jar. you need the full jar.

**Comment by shortybsd** [comment]
Just have ServerTools-CORE-1.8.9-3.0.0.131.jar

**Comment by matthewprenger** [comment]
Just tested and cannot verify. Please give me your ***FULL*** fml log using Gist/Pastebin.

**Comment by shortybsd** [comment]
https://gist.github.com/shortybsd/78af8797d80b7eb29bb9

**Comment by matthewprenger** [comment]
\*Sigh\* Looks like someone else is shipping a different version of configurate. I'll need to repack it too.

**Comment by matthewprenger** [comment]
@shortybsd Please try this build and report back if the problem is fixed: http://files.minecraftforge.net/maven/info/servertools/core/ServerTools-CORE/1.8.9-3.0.0.132/ServerTools-CORE-1.8.9-3.0.0.132.jar

**Comment by shortybsd** [comment]
Works great, thanks Matthew!

**Comment by matthewprenger** [comment]
/realoadmotd and /voice should work so please open an issue if they don't. The block logger got removed in 1.8.9 because it was a half-baked effort and really wasn't useful the way it was implemented.
